namespace: dev
contour: dev
secret_refreshInterval: "1h"
env:
  base_url: chat2desk.tech
imagePullSecrets:
  - name: image-pull-secret
Name: dev-iac-test1
groups:
  main:
    probes: false
    SERVICE_ACCOUNT: default
    enabled: true
    registry: registry.gitlab.io
    replicas: 1
    targetport: 80  
    version: latest
    reloader: true
    ingress:
      cluster_issuer: letsencrypt-prod
    probe:
      liveness: /health
      readiness: /ping
      startup: /health
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
    secret:
      ASPNETCORE_ENVIRONMENT: dev
    env:
      config:
        - name: PSQL_PASS
        - name: RAILS_MYSQL_PASS
        - name: HD_MYSQL_PASS
        - name: LC_MYSQL_PASS
        - name: LC2_MYSQL_PASS
        - name: STATS_MYSQL_PASS
        - name: GATEWAY_MYSQL_PASS
        - name: WS_MYSQL_PASS
        - name: PSQL_USER
        - name: PSQL_HOST
        - name: PSQL_DB
        - name: PSQL_PORT
        - name: REDIS_HOST
        - name: REDIS_PORT
        - name: REDIS_PASS
        - name: MYSQL_HOST
        - name: MYSQL_PORT
        - name: RAILS_MYSQL_USER
        - name: HD_MYSQL_USER
        - name: LC_MYSQL_USER
        - name: LC2_MYSQL_USER
        - name: STATS_MYSQL_USER
        - name: GATEWAY_MYSQL_USER
        - name: WS_MYSQL_USER
        - name: RAILS_ENV
        - name: RAKE_ENV
        - name: NODE_ENV
        - name: MIX_ENV
        - name: SSL
        - name: SHOW_SBERBOT
        - name: LOG_LEVEL
        - name: RAILS_LOG_TO_STDOUT
        - name: TZ
        - name: SUPERCOMPANY
        - name: SUPERPASS
        - name: AD_COMPANY_ID
        - name: STORAGE_PROVIDER
        - name: STORAGE_CONFIG
        - name: FB_CLIENT_ID
        - name: FB_CLIENT_SECRET
        - name: TG_BOT_EN
        - name: TG_BOT_RU
        - name: CLICKER_API
        - name: SSL_CACERTFILE
        - name: SMTP_ADDRESS
        - name: SMTP_PORT
        - name: SMTP_USER_NAME
        - name: SMTP_PASSWORD
        - name: SMTP_ENABLE_STARTTLS
      urls:
        - name: HELPDESK
          value: 'helpdesk.{{ .Values.namespace }}'
        - name: GATEWAY
          value: 'gateway.{{ .Values.namespace }}'
        - name: RAILS_HD
          value: 'rails-helpdesk.{{ .Values.namespace }}'
        - name: GW
          value: 'phoenix-gateway.{{ .Values.namespace }}'
        - name: STATS
          value: 'stat.{{ .Values.namespace }}'
        - name: STORAGE
          value: 'storage.{{ .Values.namespace }}'
        - name: LCHAT
          value: 'livechat.{{ .Values.namespace }}'
        - name: LCHAT_V2
          value: 'livechatv2.{{ .Values.namespace }}'
        - name: HD_URL 
          value: 'https://{{ .Values.namespace }}.{{ .Values.env.base_url }}'
        - name: GW_URL
          value: 'https://gw-{{ .Values.namespace }}.{{ .Values.env.base_url }}'
        - name: ROR_URL
          value: 'https://ror-{{ .Values.namespace }}.{{ .Values.env.base_url }}'
        - name: LC_URL
          value: 'https://livechat-{{ .Values.namespace }}.{{ .Values.env.base_url }}'
        - name: LC2_URL
          value: 'https://livechatv2-{{ .Values.namespace }}.{{ .Values.env.base_url }}'
        - name: GATEWAY_URL
          value: 'https://gateway-{{ .Values.namespace }}.{{ .Values.env.base_url }}'
        - name: STATS_URL
          value: 'https://stats-{{ .Values.namespace }}.{{ .Values.env.base_url }}'
        - name: LC2_WS_URL
          value: 'wss://livechatv2-{{ .Values.namespace }}.{{ .Values.env.base_url }}/widget_ws_new'
        - name: STORAGE_URL
          value: 'https://storage-{{ .Values.namespace }}.{{ .Values.env.base_url }}'
        - name: WS_URL
          value: 'wss://ror-{{ .Values.namespace }}.{{ .Values.env.base_url }}'
        - name: RAILS_LIVECHAT_V2_WS
          value: 'wss://livechatv2-{{ .Values.namespace }}.{{ .Values.env.base_url }}/widget_ws_new'
        - name: RAILS_LIVECHAT_V2_PATH
          value: 'https://livechatv2-{{ .Values.namespace }}.{{ .Values.env.base_url }}'
        - name: CLICKER_API_URL 
          value: 'http://clicker_api.{{ .Values.namespace }}:4005'
        - name: KRB_URL 
          value: 'https://kerberos-{{ .Values.namespace }}.{{ .Values.env.base_url }}'
        - name: STORAGE_API_URL 
          value: 'http://storage-api.{{ .Values.namespace }}'
        - name: SMART_SCRIPTS_URL 
          value: 'http://smart-scripts.{{ .Values.namespace }}'
        - name: INSTA_LOCAL_ROUTER 
          value: 'http://insta-router-{{ .Values.namespace }}.{{ .Values.env.base_url }}'
        - name: INSTANCE_HOSTS 
          value: '["http://insta-service.{{ .Values.namespace }}"]'
      
    apps:
      rails-helpdesk:
        image:
          name: registry.gitlab.io/backend/api
          tag: 1.2
        strategyType: RollingUpdate
        targetport: 5000
        resources:
          requests:
            cpu: 200m
            memory: 2641Mi
          limits:
            cpu: 400m
            memory: 2641Mi
        probes:
          liveness:
            path: /health
          readiness:
            path: /ping
          startup:
            path: /health
        service:
          port: 8080
          targetport: 8080
        ingress:
          host: dev.xyz.com
          class: nginx-internal
        pod:
          annotations:
            argocd.argoproj.io/sync-wave: "2"
        secret:
          Swagger__Enable: "true"
        serviceAccount:
          annotations:
            app: app1
        autoscaling:
          minReplicas: 1
          maxReplicas: 2
            
      helpdesk:
        image:
          name: registry.gitlab.io/backend/proxy
          tag: 1.2
        strategyType: RollingUpdate
        targetport: 5000
        resources:
          requests:
            cpu: 20m
            memory: 2641Mi
          limits:
            memory: 2641Mi
        probes:
          liveness:
            path: /health
          readiness:
            path: /ping
          startup:
            path: /health
        service:
          port: 8081
          targetport: 8081
        ingress:
          host: dev.zyx.com
          class: nginx-internal
        pod:
          annotations:
            argocd.argoproj.io/sync-wave: "2"
        secret:
          Swagger__Enable: "true"
        serviceAccount:
          annotations:
            app: app2
        autoscaling:
          minReplicas: 1
          maxReplicas: 2