{{- range $appName, $app := .Values.groups.main.apps }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $appName }}-deployment
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ $appName }}
    contour: {{ $.Values.contour }}
  {{- with $app.pod.annotations }}
  annotations:
    {{- toYaml $app.pod.annotations | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ $.Values.groups.main.replicas }}
  strategy:
    type: {{ $app.strategyType }}
  selector:
    matchLabels:
      app: {{ $appName }}
      {{- toYaml $app.selectorLabels | nindent 8 }}
  template:
    metadata:
      labels:
        app: {{ $appName }}
        contour: {{ $.Values.contour }}
      {{- with $app.pod.annotations }}
      annotations:
        {{- toYaml $app.pod.annotations | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName:  {{ $app.serviceAccountName  }}
      imagePullSecrets:
        {{- toYaml $.Values.imagePullSecrets | nindent 8 }}
      securityContext:
        {{- toYaml $app.podSecurityContext | nindent 8 }}
      # Начало секции initContainers
      {{- with $app.initContainers }}
      initContainers:
        {{- range . }}
        - name: {{ .name }}
          image: {{ .image }}
          command: {{ toYaml .command | nindent 12 }}
          envFrom:
            - secretRef:
                name: {{ $.Values.Name }}-secret
          # Используем глобальные переменные env для всех приложений
          env:
            {{- range $.Values.groups.main.env.urls }}
            - name: {{ .name }}
              value: {{ tpl .value $ }}
            {{- end }}
          

          {{- with .volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
      {{- end }}
      # Конец секции initContainers

      containers:
        - name: {{ $appName }}
          securityContext:
            {{- toYaml $app.securityContext | nindent 12 }}
          image: "{{ $app.image.name }}:{{ $app.image.tag }}"
          imagePullPolicy: {{ $app.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ $.Values.Name }}-secret
          # Используем глобальные переменные env для всех приложений
          env:
            {{- range $.Values.groups.main.env.urls }}
            - name: {{ .name }}
              value: {{ tpl .value $ }}
            {{- end }}
            
          {{- if $app.commands }}
            {{- if $app.commands.enabled }}
            command: {{ toYaml $app.commands.command }}
            args: {{ toYaml $app.commands.args }}
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ $app.targetport }}
              protocol: TCP
          {{- if $app.resources }}
          resources:
            requests:
              cpu: {{ $app.resources.requests.cpu }}
              memory: {{ $app.resources.requests.memory }}
            limits:
              cpu: {{ $app.resources.limits.cpu | default "500m" }}
              memory: {{ $app.resources.limits.memory }}
          {{- end }}
          {{- if $app.probes.liveness }}
          livenessProbe:
            httpGet:
              path: {{ $app.probes.liveness.path }}
              port: {{ $app.targetport }}
            initialDelaySeconds: {{ $app.probes.liveness.initialDelaySeconds | default 10 }}
            periodSeconds: {{ $app.probes.liveness.periodSeconds | default 10 }}
          {{- end }}
          {{- if $app.probes.readiness }}
          readinessProbe:
            httpGet:
              path: {{ $app.probes.readiness.path }}
              port: {{ $app.targetport }}
            initialDelaySeconds: {{ $app.probes.readiness.initialDelaySeconds | default 5 }}
            periodSeconds: {{ $app.probes.readiness.periodSeconds | default 5 }}
          {{- end }}
          {{- if $app.probes.startup }}
          startupProbe:
            httpGet:
              path: {{ $app.probes.startup.path }}
              port: {{ $app.targetport }}
            initialDelaySeconds: 10
            periodSeconds: 10
          {{- end }}
          volumeMounts:
            {{- with $app.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- with $app.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      nodeSelector:
        {{- toYaml $.Values.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml $.Values.affinity | nindent 8 }}
      tolerations:
        {{- toYaml $.Values.tolerations | nindent 8 }}
---
{{- end }}