apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $.Values.Name }}-external-secret
  namespace:  {{ $.Values.namespace }}  # Namespace, в котором будет создан k8s-секрет
spec:
  refreshInterval: {{ $.Values.secret_refreshInterval }}
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: {{ $.Values.Name }}-secret
    creationPolicy: Owner
  data:
    {{- range .Values.groups.main.env.config }}
    - secretKey: {{ .name }}
      remoteRef:
        key: {{ $.Values.namespace }}
        property: "{{ .name }}"
    {{- end }}