{{- range $appName, $app := .Values.groups.main.apps }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $appName }}-svc
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ $appName }}
    contour: {{ $.Values.contour }}
spec:
  type: {{ $app.service.type | default "ClusterIP" }}
  ports:
    - port: {{ $app.service.port | default 80 }}
      targetPort: {{ $app.service.targetport | default 80 }}
      protocol: TCP
      name: http
  selector:
    app: {{ $appName }}
---
{{- end }}
