{{- range $appName, $app := .Values.groups.main.apps }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $appName }}-sa
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ $appName }}
    contour: {{ $.Values.contour }}
  {{- with $app.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ $app.serviceAccount.automount }}
---
{{- end }}